#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+title: Taller de Comandos Linux
#+date: 2026-06-18
#+author: Sebastián Josué Zúñiga Mendoza
#+email: sebastian.zuniga@epn.edu.ec
#+language: Español
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.7.5)
#+cite_export:

#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_footnote_command: \footnote{%s%s}
#+latex_engraved_theme:
#+latex_compiler: pdflatex

#+latex_header: \usepackage{fancyhdr}
#+latex_header: \usepackage[top=25mm, left=25mm, right=25mm]{geometry}
#+latex_header: \usepackage{longtable}
#+latex_header: \fancyhead[R]{}
#+latex_header: \setlength\headheight{43.0pt} 



#+begin_export latex
\fancyhead[C]{\includegraphics[scale=0.05]{../images/logoEPN.jpg}\\
ESCUELA POLITÉCNICA NACIONAL\\FACULTAD DE INGENIERÍA DE SISTEMAS\\
ARQUITECTURA DE COMPUTADORES}
\thispagestyle{fancy}
#+end_export


* Objetivos

- Conocer el funcionamiento del terminal de /Linux/
- Aprender a manejar comandos del terminal de /Linux/

* Instrucciones
Este taller/tutorial de comandos de Linux tiene por objetivo ejercitar
en la aplicación de comandos estudiados en clase. Para esto siga las
Instrucciones indicadas en cada uno de los numerales. Ejecute los
ejercicios llenando los comandos adecuados dentro de los bloques de
código de Emacs Org. Los resultados de la ejecución se obtienen
haciendo ~C-c C-c~

Para todos los ejercicios se sugiere o bien usar directamente un
distro de /Linux/ o el /WSL/ configurado para la clase de
/Arquitectura de Computadores/.

1. Utilice ~cd~ para localizarse en la posición de home de su usuario y
   verifique ejecutando el comando ~pwd~
   #+begin_src shell :exports both
    cd
    pwd
   #+end_src

   #+RESULTS:
   : /home/leningfe-epn

2. Cree tres directorios denominados FashionData, Train y
   Test. Verifique usando el comando ~ls~
   #+begin_src shell :exports both
     cd
     mkdir FashionData Train Test
     ls
   #+end_src

   #+RESULTS:
   | Downloads      |
   | EPN-Lectures   |
   | FashionData    |
   | Presentaciones |
   | PyProjects     |
   | Test           |
   | Train          |
   | miniforge3     |

3. Investigue sobre el comando ~wget~ y utilícelo para descargar en
   ~/FashionData los datos de train y test del /Fashion-Mnist desde el
   siguiente enlace: [[https://github.com/zalandoresearch/fashion-mnist][fashion-mnist]]
   1. Imágenes de entrenamiento:

      http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-images-idx3-ubyte.gz
   2. Etiquetas de entrenamiento:

      http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-labels-idx1-ubyte.gz 
   3. Imágenes de prueba:

      http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz
   4. Etiquetas de prueba:

      http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-labels-idx1-ubyte.gz
   #+begin_src shell :exports both
      cd
      cd FashionData
      wget  http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-images-idx3-ubyte.gz
      wget  http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-labels-idx1-ubyte.gz
      wget  http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz
      wget   http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-labels-idx1-ubyte.gz
      ls
   #+end_src

   #+RESULTS:
   | t10k-images-idx3-ubyte.gz  |
   | t10k-labels-idx1-ubyte.gz  |
   | train-images-idx3-ubyte.gz |
   | train-labels-idx1-ubyte.gz |

4. Utilice el comando ~mv~ de manera recursiva para pasar los datos de
   entrenamiento a la carpeta ~/Train
   #+begin_src shell :exports both
     mv ~/FashionData/train-images-idx3-ubyte.gz ~/Train/
     mv ~/FashionData/train-labels-idx1-ubyte.gz ~/Train/
     cd
     cd Train
     ls
   #+end_src

   #+RESULTS:
   | train-images-idx3-ubyte.gz |
   | train-labels-idx1-ubyte.gz |

5. Utilice el comando ~mv~ de manera recursiva para pasar los datos de
   prueba a la carpeta ~/Test
   #+begin_src shell :exports both
     mv ~/FashionData/t10k-* ~/Test/
     cd
     cd Test/
     ls
   #+end_src

   #+RESULTS:
   | t10k-images-idx3-ubyte.gz |
   | t10k-labels-idx1-ubyte.gz |

6. Verifique que la carpeta FashionData está vacía
   #+begin_src shell :exports both
     cd
     cd FashionData
     ls
   #+end_src

   #+RESULTS:

7. Los archivos anteriores están comprimidos. Investigue como
   descomprimir usando el comando ~tar~. Si es necesario realice la
   instalación del comando. Descomprima los archivos en sus
   respectivas carpetas. Apunte el comando utilizado para la descompresión.
   #+begin_src shell :exports both
      cd
      cd Train
      gunzip train-*
      ls
      
      cd
      cd Test
      gunzip t10k-*
      ls
   #+end_src

   #+RESULTS:
   | train-images-idx3-ubyte |
   | train-labels-idx1-ubyte |
   | t10k-images-idx3-ubyte  |
   | t10k-labels-idx1-ubyte  |

8. Una vez completa la descompresión, elimine los archivos
   .gz. Verifique las carpetas finales usando ~ls~
   #+begin_src shell :exports both
     
   #+end_src

   #+RESULTS:

 
9. Mueva recursivamente las carpetas ~/Train y ~/Test dentro de ~/FashionData
   #+begin_src shell :exports both

      mv ~/Train ~/FashionData/
      mv ~/Test  ~/FashionData/
      cd..
      cd ~/FashionData
      ls
   #+end_src

   #+RESULTS:
   | Test  |
   | Train |
   
10. Se desea realizar un registro climatológico de la ciudad de
    Quito. Para esto, escriba un script de Python/Java que permita
    obtener datos climatológicos desde el API de
    [[https://openweathermap.org/current#one][openweathermap]]. Considere la latitud y la longitud de Quito como
    (-0.2299, -78.5249), respectivamente. Los resultados obtenidos de
    la consulta al API se escriben en un archivo
    /clima-quito-hoy.csv/. Cada ejecución del script debe almacenar
    nuevos datos en el archivo. Investigue sobre *crontab* y utilícelo
    para obtener datos del API de /openweathermap/ cada 5 minutos
    mediante la ejecución de un archivo ejecutable denominado
    /get-weather.sh/. Verifique los resultados. Todas las operaciones
    se realizan en Linux o en el WSL. Las etapas del problema se
    subdividen en:
    1. Crear su API gratuito en [[https://openweathermap.org/current#one][openweathermap]]

       Clave API:"62d2107136670bd7f62c2c23cea30130"

    2. Escribir un script en Python/Java que realice la consulta al API
       y escriba los resultados en /clima-quito-hoy.csv/
       
       #+begin_src python :exports both :tangle get-weather.py
         import os
	 import csv
	 import requests
	 from datetime import datetime

		 # Constantes de configuración
		 API_KEY = "62d2107136670bd7f62c2c23cea30130"
		 LAT = "-0.2299"
		 LON = "-78.5249"
		 URL = f"https://api.openweathermap.org/data/2.5/weather?lat={LAT}&lon={LON}&appid={API_KEY}&units=metric&lang=es"
		 NOMBRE_ARCHIVO = os.path.join(
                                     BASE_DIR,
                                     "CityWeather",
                                     "clima-quito.hoy.csv"
                                  )

		 def obtener_y_guardar_clima():
		     try:
			 # PETICIÓN A LA API
			 respuesta = requests.get(URL)
			 # Lanza una excepción si la respuesta de la API no es exitosa (ej. 401 o 404)
		 respuesta.raise_for_status() 
		 datos = respuesta.json()

		 # EXTRAER DATOS 
		 fecha_hora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
		 temperatura = datos["main"]["temp"]
		 humedad = datos["main"]["humidity"]
		 presion = datos["main"]["pressure"]
		 descripcion = datos["weather"][0]["description"]

		 # VERIFICAR SI EL ARCHIVO EXISTE
		 archivo_existe = os.path.exists(NOMBRE_ARCHIVO)

		 # GUARDAR EN CSV
		 # mode="a" (append) asegura que los datos se agreguen al final sin borrar los existentes
		with open(NOMBRE_ARCHIVO, mode="a", newline="", encoding="utf-8") as file:
		    escritor = csv.writer(file)

		    # Si el archivo es nuevo, escribir nombres de columnas
		    if not archivo_existe:
			escritor.writerow(["Fecha_Hora", "Temperatura_C", "Humedad_Porcentaje", "Presion_hPa", "Descripcion"])

		    # Fila con los nuevos datos del clima
		    escritor.writerow([fecha_hora, temperatura, humedad, presion, descripcion])

		print(f"[{fecha_hora}] Datos guardados exitosamente en {NOMBRE_ARCHIVO}")

	    except requests.exceptions.RequestException as req_err:
		print(f"Error de red o de la API: {req_err}")
	    except KeyError as key_err:
		print(f"Error al procesar los datos de la API. Estructura inesperada: {key_err}")
	    except Exception as e:
		print(f"Ocurrió un error inesperado: {e}")

	if __name__ == "__main__":
	    obtener_y_guardar_clima()
       #+end_src
    3. Desarrollar un ejecutable /get-weather.sh/ para ejecutar el
       programa Python/Java.
       #+begin_src shell :exports both

       cd home/sebaszun-epn/
       !Para esto, primero es necesario ejecutar el comando 


       #+end_src

       #+RESULTS:
       : /home/sebaszun-epn/EPN-Lectures/iccd332ArqComp-2024-B/Talleres

    4. Configurar Crontab para la adquisición de datos. Escriba el
       comando configurado.
       
